### PR TITLE
Add page about how to set up screen readers on a Mac

### PR DESCRIPTION
**Pull request by line47**
How to install virtualBox, windows virtual machine, JAWS, and NVDA 🎉 🤖

### CODE REVIEW

**Comment by line47** [comment]
Wondering if anyone else can give this a review? I'd like to get it merged so we can point to this doc from other places 👍

**Comment by 1Copenut** [comment]
I can review if no one else is volunteering, but will have to move some things around. My Macbook is nearly hard drive maxed because of Docker and a few other things in the System glob.

**Comment by line47** [comment]
Feel free to merge when you feel @1Copenut 🚀 
@surfbird0713 did a great job reviewing 🤘

**Review by 1Copenut — APPROVED** [review]
Approving with two big thumbs up. Thank you for putting this together and running a live walk through!

**Pull request merged**
